name: hooprank
description: HoopRank mobile app (starter stubs)
publish_to: 'none'
version: 0.1.3+5
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  go_router: ^13.2.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  image_picker: ^1.1.2
  flutter_map_marker_cluster: ^1.3.6
  geolocator: ^11.0.0
  fl_chart: ^0.68.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  flutter_secure_storage: ^9.0.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#1A252F"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter_native_splash:
  color: "#1A252F"
  image: "assets/splash.png"
  android_12:
    color: "#1A252F"
    image: "assets/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/
